import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import clsx from "clsx";
const inter = Inter({ subsets: ["latin"] });
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import { Anek_Telugu } from "next/font/google";
import { Header } from "@/components/Header";
import { Footer } from "./Footer";
import { Spotlight } from "@/components/Spotlight";
import { ThemeProvider } from "@/Theme/ThemeProvider";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
export const metadata: Metadata = {
  title: "Life Advice",
  description: "Generated by create next app",
};
const AnekTelugu = Anek_Telugu({ subsets: ["latin"],
  variable:"--font-caption"
 });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en"  >
      
      <body className={cn(
         GeistSans.variable,
         GeistMono.variable,
         AnekTelugu.variable,
        "flex flex-col font-sans min-h-screen "
      )}>
           <Spotlight
        className="-top-40 left-0 md:left-60 md:-top-20"
        fill="white"
      />
       <ThemeProvider
        attribute="class"
         defaultTheme="dark" 
         enableSystem
         disableTransitionOnChange
         >
            <ReactQueryProvider >
            <Header />
        {children}
        <Footer />
    </ReactQueryProvider>
     
        </ThemeProvider>
        </body>
      
    </html>
  );
}
